// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSongMessage;
@class FLTInitializeMessage;
@class FLTPlayModeMessage;
@class FLTSongsMessage;
@class FLTPositionMessage;
@class FLTStateMessage;

@interface FLTSongMessage : NSObject
@property(nonatomic, strong, nullable) NSDictionary * song;
@end

@interface FLTInitializeMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * callbackHandle;
@end

@interface FLTPlayModeMessage : NSObject
@property(nonatomic, copy, nullable) NSString * playMode;
@end

@interface FLTSongsMessage : NSObject
@property(nonatomic, strong, nullable) NSArray * songs;
@end

@interface FLTPositionMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * position;
@property(nonatomic, strong, nullable) NSNumber * duration;
@end

@interface FLTStateMessage : NSObject
@property(nonatomic, copy, nullable) NSString * state;
@end

@protocol FLTStreamUrlCallbackApi
-(void)setStreamUrl:(FLTSongMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTStreamUrlCallbackApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTStreamUrlCallbackApi> _Nullable api);

@protocol FLTMusicPlayerControllerApi
-(void)initialize:(FLTInitializeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setPlayMode:(FLTPlayModeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)playSong:(FLTSongMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)playSongList:(FLTSongsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)playPrev:(FlutterError *_Nullable *_Nonnull)error;
-(void)playNext:(FlutterError *_Nullable *_Nonnull)error;
-(void)play:(FlutterError *_Nullable *_Nonnull)error;
-(void)pause:(FlutterError *_Nullable *_Nonnull)error;
-(void)seekTo:(FLTPositionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)addSongToPlaylistNext:(FLTSongMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)deleteSongFromPlaylist:(FLTSongMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)clearPlaylist:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTMusicPlayerControllerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTMusicPlayerControllerApi> _Nullable api);

@interface FLTStreamUrlServiceApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)retrieveStreamUrl:(FLTSongMessage*)input completion:(void(^)(NSError* _Nullable))completion;
@end
@interface FLTMusicPlayerCallbackApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onShowingSongListChanged:(FLTSongsMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onPlayingSongListChanged:(FLTSongsMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onPlayerStateChanged:(FLTStateMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onPlayingSongChanged:(FLTSongMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onPositionChanged:(FLTPositionMessage*)input completion:(void(^)(NSError* _Nullable))completion;
@end
NS_ASSUME_NONNULL_END
