// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTStreamUrlMessage;
@class FLTSongMessage;
@class FLTSongsMessage;
@class FLTPositionMessage;
@class FLTStateMessage;

@interface FLTStreamUrlMessage : NSObject
@property(nonatomic, copy, nullable) NSString * streamUrl;
@end

@interface FLTSongMessage : NSObject
@property(nonatomic, copy, nullable) NSString * plt;
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * cover;
@property(nonatomic, copy, nullable) NSString * streamUrl;
@property(nonatomic, copy, nullable) NSString * albumName;
@property(nonatomic, copy, nullable) NSString * singerName;
@end

@interface FLTSongsMessage : NSObject
@property(nonatomic, strong, nullable) NSArray * songs;
@end

@interface FLTPositionMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * position;
@property(nonatomic, strong, nullable) NSNumber * duration;
@end

@interface FLTStateMessage : NSObject
@property(nonatomic, copy, nullable) NSString * state;
@end

@interface FLTMusicPlayerDelegateApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)retrieveStreamUrl:(FLTSongMessage*)input completion:(void(^)(FLTStreamUrlMessage*, NSError* _Nullable))completion;
@end
@protocol FLTMusicPlayerControllerApi
-(void)syncPlaylist:(FLTSongsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)playSong:(FLTSongMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)play:(FlutterError *_Nullable *_Nonnull)error;
-(void)pause:(FlutterError *_Nullable *_Nonnull)error;
-(void)stop:(FlutterError *_Nullable *_Nonnull)error;
-(void)seek:(FLTPositionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTMusicPlayerControllerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTMusicPlayerControllerApi> _Nullable api);

@interface FLTMusicPlayerCallbackApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onPlayerStateChanged:(FLTStateMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onSongChanged:(FLTSongMessage*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)onPositionChanged:(FLTPositionMessage*)input completion:(void(^)(NSError* _Nullable))completion;
@end
NS_ASSUME_NONNULL_END
