// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
// @dart = 2.8
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/services.dart';

class StreamUrlMessage {
  String streamUrl;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['streamUrl'] = streamUrl;
    return pigeonMap;
  }

  // ignore: unused_element
  static StreamUrlMessage decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return StreamUrlMessage()
      ..streamUrl = pigeonMap['streamUrl'] as String;
  }
}

class SongMessage {
  String plt;
  String id;
  String name;
  String cover;
  String streamUrl;
  String albumName;
  String singerName;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['plt'] = plt;
    pigeonMap['id'] = id;
    pigeonMap['name'] = name;
    pigeonMap['cover'] = cover;
    pigeonMap['streamUrl'] = streamUrl;
    pigeonMap['albumName'] = albumName;
    pigeonMap['singerName'] = singerName;
    return pigeonMap;
  }

  // ignore: unused_element
  static SongMessage decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return SongMessage()
      ..plt = pigeonMap['plt'] as String
      ..id = pigeonMap['id'] as String
      ..name = pigeonMap['name'] as String
      ..cover = pigeonMap['cover'] as String
      ..streamUrl = pigeonMap['streamUrl'] as String
      ..albumName = pigeonMap['albumName'] as String
      ..singerName = pigeonMap['singerName'] as String;
  }
}

class SongsMessage {
  List<Object> songs;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['songs'] = songs;
    return pigeonMap;
  }

  // ignore: unused_element
  static SongsMessage decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return SongsMessage()
      ..songs = pigeonMap['songs'] as List<Object>;
  }
}

class PositionMessage {
  int position;
  int duration;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['position'] = position;
    pigeonMap['duration'] = duration;
    return pigeonMap;
  }

  // ignore: unused_element
  static PositionMessage decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return PositionMessage()
      ..position = pigeonMap['position'] as int
      ..duration = pigeonMap['duration'] as int;
  }
}

class StateMessage {
  String state;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['state'] = state;
    return pigeonMap;
  }

  // ignore: unused_element
  static StateMessage decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return StateMessage()
      ..state = pigeonMap['state'] as String;
  }
}

abstract class MusicPlayerDelegateApi {
  StreamUrlMessage retrieveStreamUrl(SongMessage arg);
  static void setup(MusicPlayerDelegateApi api) {
    {
      const BasicMessageChannel<Object> channel =
          BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerDelegateApi.retrieveStreamUrl', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object message) async {
          if (message == null) {
            return null;
          }
          final SongMessage input = SongMessage.decode(message);
          final StreamUrlMessage output = api.retrieveStreamUrl(input);
          return output.encode();
        });
      }
    }
  }
}

class MusicPlayerControllerApi {
  Future<void> syncPlaylist(SongsMessage arg) async {
    final Object encoded = arg.encode();
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.syncPlaylist', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(encoded) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<void> playSong(SongMessage arg) async {
    final Object encoded = arg.encode();
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.playSong', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(encoded) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<void> play() async {
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.play', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(null) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<void> pause() async {
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.pause', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(null) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<void> stop() async {
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.stop', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(null) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }

  Future<void> seek(PositionMessage arg) async {
    final Object encoded = arg.encode();
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerControllerApi.seek', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(encoded) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      // noop
    }
  }
}

abstract class MusicPlayerCallbackApi {
  void onPlayerStateChanged(StateMessage arg);
  void onSongChanged(SongMessage arg);
  void onPositionChanged(PositionMessage arg);
  static void setup(MusicPlayerCallbackApi api) {
    {
      const BasicMessageChannel<Object> channel =
          BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerCallbackApi.onPlayerStateChanged', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object message) async {
          if (message == null) {
            return;
          }
          final StateMessage input = StateMessage.decode(message);
          api.onPlayerStateChanged(input);
          return;
        });
      }
    }
    {
      const BasicMessageChannel<Object> channel =
          BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerCallbackApi.onSongChanged', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object message) async {
          if (message == null) {
            return;
          }
          final SongMessage input = SongMessage.decode(message);
          api.onSongChanged(input);
          return;
        });
      }
    }
    {
      const BasicMessageChannel<Object> channel =
          BasicMessageChannel<Object>('dev.flutter.pigeon.MusicPlayerCallbackApi.onPositionChanged', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object message) async {
          if (message == null) {
            return;
          }
          final PositionMessage input = PositionMessage.decode(message);
          api.onPositionChanged(input);
          return;
        });
      }
    }
  }
}
