// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package app.dier.music;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.ArrayList;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings("unused")
public class MusicMessages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class StreamUrlMessage {
    private String streamUrl;
    public String getStreamUrl() { return streamUrl; }
    public void setStreamUrl(String setterArg) { this.streamUrl = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("streamUrl", streamUrl);
      return toMapResult;
    }
    static StreamUrlMessage fromMap(HashMap map) {
      StreamUrlMessage fromMapResult = new StreamUrlMessage();
      Object streamUrl = map.get("streamUrl");
      fromMapResult.streamUrl = (String)streamUrl;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SongMessage {
    private String plt;
    public String getPlt() { return plt; }
    public void setPlt(String setterArg) { this.plt = setterArg; }

    private String id;
    public String getId() { return id; }
    public void setId(String setterArg) { this.id = setterArg; }

    private String name;
    public String getName() { return name; }
    public void setName(String setterArg) { this.name = setterArg; }

    private String cover;
    public String getCover() { return cover; }
    public void setCover(String setterArg) { this.cover = setterArg; }

    private String streamUrl;
    public String getStreamUrl() { return streamUrl; }
    public void setStreamUrl(String setterArg) { this.streamUrl = setterArg; }

    private String albumName;
    public String getAlbumName() { return albumName; }
    public void setAlbumName(String setterArg) { this.albumName = setterArg; }

    private String singerName;
    public String getSingerName() { return singerName; }
    public void setSingerName(String setterArg) { this.singerName = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("plt", plt);
      toMapResult.put("id", id);
      toMapResult.put("name", name);
      toMapResult.put("cover", cover);
      toMapResult.put("streamUrl", streamUrl);
      toMapResult.put("albumName", albumName);
      toMapResult.put("singerName", singerName);
      return toMapResult;
    }
    static SongMessage fromMap(HashMap map) {
      SongMessage fromMapResult = new SongMessage();
      Object plt = map.get("plt");
      fromMapResult.plt = (String)plt;
      Object id = map.get("id");
      fromMapResult.id = (String)id;
      Object name = map.get("name");
      fromMapResult.name = (String)name;
      Object cover = map.get("cover");
      fromMapResult.cover = (String)cover;
      Object streamUrl = map.get("streamUrl");
      fromMapResult.streamUrl = (String)streamUrl;
      Object albumName = map.get("albumName");
      fromMapResult.albumName = (String)albumName;
      Object singerName = map.get("singerName");
      fromMapResult.singerName = (String)singerName;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SongsMessage {
    private ArrayList songs;
    public ArrayList getSongs() { return songs; }
    public void setSongs(ArrayList setterArg) { this.songs = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("songs", songs);
      return toMapResult;
    }
    static SongsMessage fromMap(HashMap map) {
      SongsMessage fromMapResult = new SongsMessage();
      Object songs = map.get("songs");
      fromMapResult.songs = (ArrayList)songs;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PositionMessage {
    private Long position;
    public Long getPosition() { return position; }
    public void setPosition(Long setterArg) { this.position = setterArg; }

    private Long duration;
    public Long getDuration() { return duration; }
    public void setDuration(Long setterArg) { this.duration = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("position", position);
      toMapResult.put("duration", duration);
      return toMapResult;
    }
    static PositionMessage fromMap(HashMap map) {
      PositionMessage fromMapResult = new PositionMessage();
      Object position = map.get("position");
      fromMapResult.position = (position == null) ? null : ((position instanceof Integer) ? (Integer)position : (Long)position);
      Object duration = map.get("duration");
      fromMapResult.duration = (duration == null) ? null : ((duration instanceof Integer) ? (Integer)duration : (Long)duration);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class StateMessage {
    private String state;
    public String getState() { return state; }
    public void setState(String setterArg) { this.state = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("state", state);
      return toMapResult;
    }
    static StateMessage fromMap(HashMap map) {
      StateMessage fromMapResult = new StateMessage();
      Object state = map.get("state");
      fromMapResult.state = (String)state;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java.*/
  public static class MusicPlayerDelegateApi {
    private final BinaryMessenger binaryMessenger;
    public MusicPlayerDelegateApi(BinaryMessenger argBinaryMessenger){
      this.binaryMessenger = argBinaryMessenger;
    }
    public interface Reply<T> {
      void reply(T reply);
    }
    public void retrieveStreamUrl(SongMessage argInput, Reply<StreamUrlMessage> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerDelegateApi.retrieveStreamUrl", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        HashMap outputMap = (HashMap)channelReply;
        @SuppressWarnings("ConstantConditions")
        StreamUrlMessage output = StreamUrlMessage.fromMap(outputMap);
        callback.reply(output);
      });
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface MusicPlayerControllerApi {
    void syncPlaylist(SongsMessage arg);
    void playSong(SongMessage arg);
    void play();
    void pause();
    void stop();
    void seek(PositionMessage arg);

    /** Sets up an instance of `MusicPlayerControllerApi` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, MusicPlayerControllerApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.syncPlaylist", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              SongsMessage input = SongsMessage.fromMap((HashMap)message);
              api.syncPlaylist(input);
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.playSong", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              SongMessage input = SongMessage.fromMap((HashMap)message);
              api.playSong(input);
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.play", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              api.play();
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.pause", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              api.pause();
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.stop", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              api.stop();
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerControllerApi.seek", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              PositionMessage input = PositionMessage.fromMap((HashMap)message);
              api.seek(input);
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java.*/
  public static class MusicPlayerCallbackApi {
    private final BinaryMessenger binaryMessenger;
    public MusicPlayerCallbackApi(BinaryMessenger argBinaryMessenger){
      this.binaryMessenger = argBinaryMessenger;
    }
    public interface Reply<T> {
      void reply(T reply);
    }
    public void onPlayerStateChanged(StateMessage argInput, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerCallbackApi.onPlayerStateChanged", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        callback.reply(null);
      });
    }
    public void onSongChanged(SongMessage argInput, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerCallbackApi.onSongChanged", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        callback.reply(null);
      });
    }
    public void onPositionChanged(PositionMessage argInput, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MusicPlayerCallbackApi.onPositionChanged", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        callback.reply(null);
      });
    }
  }
  private static HashMap wrapError(Exception exception) {
    HashMap<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
